FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Install Python and opencv dependencies
RUN apt-get update && apt-get install -y python3.10 python3-pip ffmpeg libsm6 libxext6

# Istall ONNX runtime with GPU support
RUN pip3 install flatbuffers numpy packaging protobuf sympy
RUN pip3 install onnxruntime-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/

# Install additional dependencies for serving
COPY requirements_serve.txt .
RUN pip3 install -r requirements_serve.txt