FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3.10 python3-pip
RUN ln -s /usr/bin/python3.10 /usr/bin/python


# Istall ONNX runtime with GPU support
RUN pip install flatbuffers numpy packaging protobuf sympy
RUN pip install onnxruntime-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/

# Install additional dependencies for serving
COPY requirements_serve.txt .
RUN pip install -r requirements_serve.txt